wifi_ssid: "..."
wifi_password: "..."
solaris_ap_fallback_password: "..."
solaris_api_encryption_key: "..."
solaris_ota_password: "..."
solaris_web_server_username: "..."
solaris_web_server_password: "..."